Repository TurbineAnalytics/docker-spark-cassandra, pull requests merged in 2019-04, with the labels that each got.

#28 FEATURE / TAMAPI-2552 bumped connector version
  Dockerfile
Labels: enhancement

#29 bugfix / TAMAPI-2554 Fix docker build on travis
  Dockerfile
Labels: bug

#30 release/v1.4.0 into production
  Dockerfile
Labels: release
